name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Use your desired Java version
          distribution: 'temurin'
          cache: 'gradle'

      # - name: Import GPG private key
      #   run: |
      #     echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import --passphrase "${{ secrets.GPG_PASSPHRASE }}"

      - name: Publish to Sonatype
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          signingPassword: ${{ secrets.GPG_PASSPHRASE }}
